[build]
  command = "cd client && npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"

# Functions configuration (if needed)
[functions]
  directory = "netlify/functions"

# Edge functions (if needed)
[[edge_functions]]
  path = "/api/*"
  function = "api-proxy"
